export const features = {
  woodenDoor: {
    name: 'door',
    tiles: ['woodenDoorClosed', 'woodenDoorOpen'],
    tag: ['memorable', 'feature', 'blocksLight', 'blocksMovement', 'isClosed', 'door'],
    trodOn: 'You carefully backflip through the door.',
    tileTriggers: ['isClosed', 'isOpen'],
  },
  woodenDoorVertical: {
    name: 'door',
    tiles: ['woodenDoorVerticalClosed', 'woodenDoorVerticalOpen'],
    tag: [
      'memorable',
      'feature',
      'blocksLight',
      'blocksMovement',
      'isClosed',
      'door',
      'isVertical',
    ],
    trodOn: 'You carefully backflip through the door.',
    tileTriggers: ['isClosed', 'isOpen'],
  },
  woodenDoorVerticalTop: {
    name: 'door',
    tiles: ['woodenDoorVerticalClosedTop', 'woodenDoorVerticalOpenTop'],
    tag: [
      'memorable',
      'feature',
      'blocksLight',
      'blocksMovement',
      'isClosed',
      'door',
      'isVertical',
    ],
    trodOn: 'You carefully backflip through the door.',
    tileTriggers: ['isClosed', 'isOpen'],
  },
  stoneDoor: {
    name: 'door',
    tiles: ['stoneDoorClosed', 'stoneDoorOpen'],
    tag: ['memorable', 'feature', 'blocksLight', 'blocksMovement', 'isClosed', 'door'],
    trodOn: 'You carefully backflip through the door.',
    tileTriggers: ['isClosed', 'isOpen'],
    tileVariant: ['stoneDoorV', 'stoneDoorVNorth'],
  },
  stoneDoorVertical: {
    name: 'door',
    tiles: ['stoneDoorVerticalClosed', 'stoneDoorVerticalOpen'],
    tag: [
      'memorable',
      'feature',
      'blocksLight',
      'blocksMovement',
      'isClosed',
      'door',
      'isVertical',
    ],
    trodOn: 'You carefully backflip through the door.',
    tileTriggers: ['isClosed', 'isOpen'],
  },
  stoneDoorVerticalTop: {
    name: 'door',
    tiles: ['stoneDoorVerticalClosedTop', 'stoneDoorVerticalOpenTop'],
    tag: [
      'memorable',
      'feature',
      'blocksLight',
      'blocksMovement',
      'isClosed',
      'door',
      'isVertical',
    ],
    trodOn: 'You carefully backflip through the door.',
    tileTriggers: ['isClosed', 'isOpen'],
  },
  web: {
    name: 'web',
    tiles: ['web1'],
    tag: ['feature'],
  },
  cactus: {
    name: 'cactus',
    tiles: ['cactus'],
    tag: ['feature'],
  },
  lilypad1: {
    name: 'lilypad',
    tiles: ['lilypad11', 'lilypad12'],
    tilesAutoCycle: 1000,
    tag: ['feature'],
    trodOn: 'You bounce off the lilypad.',
  },
  lilypad2: {
    name: 'lilypad',
    tiles: ['lilypad21', 'lilypad22'],
    tilesAutoCycle: 1000,
    tag: ['feature'],
    trodOn: 'You bounce off the lilypad.',
  },
  lilypad3: {
    name: 'lilypad',
    tiles: ['lilypad31', 'lilypad32'],
    tilesAutoCycle: 1000,
    tag: ['feature'],
    trodOn: 'You bounce off the lilypad.',
  },
  lilypad4: {
    name: 'lilypad',
    tiles: ['lilypad41', 'lilypad42'],
    tilesAutoCycle: 1000,
    tag: ['feature'],
    trodOn: 'You bounce off the lilypad.',
  },
} as const

export const featuresOld = [
  {
    label: 'woodenDoor',
    name: ['door'],
    tiles: ['woodenDoorClosed', 'woodenDoorOpen'],
    tag: ['memorable', 'feature', 'blocksLight', 'blocksMovement', 'isClosed', 'door'],
    trodOn: ['You carefully backflip through the door.'],
    tileTriggers: ['isClosed', 'isOpen'],
    tileVariant: ['woodenDoorV', 'woodenDoorVNorth'],
  },
  {
    label: 'woodenDoorV',
    name: ['door'],
    tiles: ['woodenDoorVClosed', 'woodenDoorVOpen'],
    tag: [
      'memorable',
      'feature',
      'blocksLight',
      'blocksMovement',
      'isClosed',
      'door',
      'hasDoorNorth',
      'renderAbove',
    ],
    trodOn: ['You carefully backflip through the door.'],
    tileTriggers: ['isClosed', 'isOpen'],
  },
  {
    label: 'woodenDoorVNorth',
    name: ['door'],
    tiles: ['woodenDoorVClosedNorth', 'woodenDoorVOpenNorth'],
    tag: ['memorable', 'feature', 'blocksLight', 'blocksMovement', 'isClosed', 'door'],
    trodOn: ['You carefully backflip through the door.'],
    tileTriggers: ['isClosed', 'isOpen'],
  },
  {
    label: 'stoneDoor',
    name: ['door'],
    tiles: ['stoneDoorClosed', 'stoneDoorOpen'],
    tag: ['memorable', 'feature', 'blocksLight', 'blocksMovement', 'isClosed', 'door'],
    trodOn: ['You carefully backflip through the door.'],
    tileTriggers: ['isClosed', 'isOpen'],
    tileVariant: ['stoneDoorV', 'stoneDoorVNorth'],
  },
  {
    label: 'stoneDoorV',
    name: ['door'],
    tiles: ['stoneDoorVClosed', 'stoneDoorVOpen'],
    tag: [
      'memorable',
      'feature',
      'blocksLight',
      'blocksMovement',
      'isClosed',
      'door',
      'hasDoorNorth',
      'renderAbove',
    ],
    trodOn: ['You carefully backflip through the door.'],
    tileTriggers: ['isClosed', 'isOpen'],
  },
  {
    label: 'stoneDoorVNorth',
    name: ['door'],
    tiles: ['stoneDoorVClosedNorth', 'stoneDoorVOpenNorth'],
    tag: ['memorable', 'feature', 'blocksLight', 'blocksMovement', 'isClosed', 'door'],
    trodOn: ['You carefully backflip through the door.'],
    tileTriggers: ['isClosed', 'isOpen'],
  },
]
