export const outdoorRuin = [
  '        %m          ',
  '     ###%m%#m       ',
  '     %mvv%vvmm      ',
  '     mmvvvv#########',
  '     #mvvvv+vvvvvvv#',
  '###+##mvvvv#########',
  '%mmmmmmvdvv+vvvSvvv#',
  'vvvvvvvvvvv#########',
  'mmvvvvvvvvv+vvvvvvv#',
  '%mmmmmmvvvv#########',
  '######mvvvm%m       ',
  '    %#mvvmmmm       ',
  '     #mmmmmmm       ',
  '     #mm%mmm        ',
  '     ###m%mm        ',
  '      m%mm          ',
  '      mm%m          ',
]
