export const outdoorRuin = [
  '        %m          ',
  '     ###%m%#m       ',
  '     #mvv%vvmm      ',
  '     mmvvvv#########',
  '     #mvvvv+vvvvvvv#',
  '###+##mvvvv#########',
  '#mmmmmmvvvv+vvvSvvv#',
  'vvvvvvvvdvv#########',
  'mmvvvvvvvvv+vvvvvvv#',
  '#mmmmmmvvvv#########',
  '######mvvvm#        ',
  '    %#mvvmmm        ',
  '     #mmmmmm        ',
  '     #mm%mmm        ',
  '     ####%mm        ',
  '       %            ',
  '        %           ',
]
